services:
  db:
    image: mysql:${MYSQL_VERSION}
    container_name: wp_db
    command: ["--default-authentication-plugin=mysql_native_password","--lower_case_table_names=2"]
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  wordpress:
    image: wordpress:${WP_VERSION}
    container_name: wp_app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${WP_PORT}:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_TABLE_PREFIX: ${WP_TABLE_PREFIX}
    volumes:
      - wp_html:/var/www/html
      - ./../pepecapiro:/var/www/html/wp-content/themes/pepecapiro
    working_dir: /var/www/html

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: wp_pma
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${PMA_PORT}:80"

  wpcli:
    image: wordpress:cli
    container_name: wp_cli
    depends_on:
      db:
        condition: service_healthy
      wordpress:
        condition: service_started
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    working_dir: /var/www/html
    volumes:
      - wp_html:/var/www/html
      - ./../pepecapiro:/var/www/html/wp-content/themes/pepecapiro

volumes:
  db_data:
  wp_html:
