name: Diagnóstico - Front Page Line 57

on:
  workflow_dispatch:

env:
  SSH_HOST: ${{ secrets.PEPE_HOST }}
  SSH_PORT: ${{ secrets.PEPE_PORT }}
  SSH_USER: ${{ secrets.PEPE_USER }}
  WP_ROOT: /home/u525829715/domains/pepecapiro.com/public_html

jobs:
  diagnostico-front-page:
    runs-on: ubuntu-latest
    steps:
      - name: Cargar clave SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.PEPE_SSH_KEY }}

      - name: Preparar known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -T 5 -p "$SSH_PORT" "$SSH_HOST" >> ~/.ssh/known_hosts

      - name: Mostrar líneas 50-65 de front-page.php
        run: |
          ssh -p "$SSH_PORT" "$SSH_USER@$SSH_HOST" "
            cd $WP_ROOT/wp-content/themes/pepecapiro
            echo '=== front-page.php líneas 50-65 ==='
            sed -n '50,65p' front-page.php | cat -n
            
            echo ''
            echo '=== Syntax check front-page.php ==='
            php -l front-page.php 2>&1 || echo 'Error de sintaxis detectado'
          "

      - name: Comparar con versión del repo
        uses: actions/checkout@v4

      - name: Diff local vs producción
        run: |
          echo '=== Líneas 50-65 de front-page.php EN REPO ==='
          sed -n '50,65p' pepecapiro/front-page.php | cat -n
