name: Hotfix - Cache Flush v0.3.21

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Confirmar ejecución (yes/no)'
        required: true
        default: 'yes'

env:
  SSH_HOST: ${{ secrets.PEPE_HOST }}
  SSH_PORT: ${{ secrets.PEPE_PORT }}
  SSH_USER: ${{ secrets.PEPE_USER }}
  WP_ROOT: /home/u525829715/domains/pepecapiro.com/public_html

jobs:
  cache-flush:
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm == 'yes'
    steps:
      - name: Checkout (para contexto)
        uses: actions/checkout@v4

      - name: Cargar clave SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.PEPE_SSH_KEY }}

      - name: Preparar known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -T 5 -p "$SSH_PORT" "$SSH_HOST" >> ~/.ssh/known_hosts

      - name: Test conexión SSH
        run: |
          ssh -o BatchMode=yes -p "$SSH_PORT" "$SSH_USER@$SSH_HOST" "echo '✓ SSH OK' && uname -a"

      - name: Flush WordPress cache y rewrite rules
        run: |
          ssh -p "$SSH_PORT" "$SSH_USER@$SSH_HOST" "
            set -e
            cd $WP_ROOT
            echo '🔄 Flushing WordPress cache...'
            wp cache flush
            echo '✓ Cache flushed'
            
            echo '🔄 Flushing rewrite rules...'
            wp rewrite flush --hard
            echo '✓ Rewrite rules flushed'
            
            echo '🔄 Purging LiteSpeed cache...'
            wp litespeed-purge all || echo '⚠️ LiteSpeed not available'
            
            echo '🔄 Deleting transients...'
            wp transient delete --all
            echo '✓ Transients deleted'
          "

      - name: Limpiar cache Rank Math sitemaps
        run: |
          ssh -p "$SSH_PORT" "$SSH_USER@$SSH_HOST" "
            cd $WP_ROOT
            echo '🔄 Clearing Rank Math sitemap cache...'
            PREFIX=\$(wp db prefix)
            wp db query \"DELETE FROM \\\${PREFIX}options WHERE option_name LIKE 'rank_math_sitemap_%';\"
            echo '✓ Rank Math sitemap cache cleared'
          "

      - name: Warm-up sitemaps
        run: |
          ssh -p "$SSH_PORT" "$SSH_USER@$SSH_HOST" "
            cd $WP_ROOT
            echo '🔄 Warming up sitemaps...'
            curl -sS https://pepecapiro.com/sitemap_index.xml >/dev/null && echo '✓ sitemap_index.xml OK' || echo '⚠️ sitemap_index failed'
            curl -sS https://pepecapiro.com/post-sitemap.xml >/dev/null && echo '✓ post-sitemap.xml OK' || echo '⚠️ post-sitemap failed'
          "

      - name: Verificar estado final
        run: |
          ssh -p "$SSH_PORT" "$SSH_USER@$SSH_HOST" "
            cd $WP_ROOT
            echo '📊 Estado actual:'
            wp theme list | grep pepecapiro
            wp plugin list --status=active | head -n 10
            echo 'Home URL:' \$(wp option get home)
            echo 'Site URL:' \$(wp option get siteurl)
          "

      - name: Test HTTP final
        run: |
          echo '🌐 Testing HTTP endpoints...'
          curl -sS -I https://pepecapiro.com/ | head -n 1
          curl -sS -I https://pepecapiro.com/en/ | head -n 1
          echo '✓ HTTP tests completed'

      - name: Resumen
        run: |
          echo "✅ Hotfix completado"
          echo "Operaciones ejecutadas:"
          echo "  - wp cache flush"
          echo "  - wp rewrite flush --hard"
          echo "  - wp litespeed-purge all"
          echo "  - wp transient delete --all"
          echo "  - Rank Math sitemap cache cleared"
          echo "  - Sitemaps warm-up"
          echo ""
          echo "Verificar sitio: https://pepecapiro.com/"
