name: Lighthouse Audit (Mobile + Desktop)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Node.js (LTS)
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Setup Google Chrome
        uses: browser-actions/setup-chrome@v1
        id: setup-chrome

      - name: Install Lighthouse CLI
        run: |
          npm -g install lighthouse @lhci/cli

      - name: Prepare reports directory
        run: |
          mkdir -p lighthouse_reports

      - name: Run Lighthouse (mobile) for target URLs
        env:
          CHROME_PATH: ${{ steps.setup-chrome.outputs.chrome-path }}
        run: |
          set -euo pipefail
          base="https://pepecapiro.com"
          run_lh(){
            local path="$1"; local name="$2";
            echo "==> Auditing $path -> $name"
            if ! lighthouse "${base}${path}" \
              --output=json --output=html \
              --output-path="lighthouse_reports/${name}" \
              --preset=perf \
              --emulated-form-factor=mobile \
              --throttling-method=devtools \
              --chrome-flags="--headless=new --no-sandbox --disable-gpu" \
              ${CHROME_PATH:+--chrome-path="$CHROME_PATH"}; then
              echo "[retry] Reintentando $path -> $name"
              lighthouse "${base}${path}" \
                --output=json --output=html \
                --output-path="lighthouse_reports/${name}" \
                --preset=perf \
                --emulated-form-factor=mobile \
                --throttling-method=devtools \
                --chrome-flags="--headless=new --no-sandbox --disable-gpu" \
                ${CHROME_PATH:+--chrome-path="$CHROME_PATH"}
            fi
            # Normalizar nombres
            mv "lighthouse_reports/${name}.report.json" "lighthouse_reports/${name}.json"
            mv "lighthouse_reports/${name}.report.html" "lighthouse_reports/${name}.html"
          }

          run_lh "/"              "home"
          run_lh "/en/"           "en-home"
          run_lh "/sobre-mi/"     "sobre-mi"
          run_lh "/en/about/"     "en-about"
          run_lh "/proyectos/"    "proyectos"
          run_lh "/en/projects/"  "en-projects"
          run_lh "/recursos/"     "recursos"
          run_lh "/en/resources/" "en-resources"
          run_lh "/contacto/"     "contacto"
          run_lh "/en/contact/"   "en-contact"

      - name: Run Lighthouse (desktop) for target URLs
        env:
          CHROME_PATH: ${{ steps.setup-chrome.outputs.chrome-path }}
        run: |
          set -euo pipefail
          base="https://pepecapiro.com"
          run_lh(){
            local path="$1"; local name="$2";
            echo "==> Auditing (desktop) $path -> ${name}-d"
            if ! lighthouse "${base}${path}" \
              --output=json --output=html \
              --output-path="lighthouse_reports/${name}-d" \
              --preset=perf \
              --emulated-form-factor=desktop \
              --throttling-method=devtools \
              --chrome-flags="--headless=new --no-sandbox --disable-gpu" \
              ${CHROME_PATH:+--chrome-path="$CHROME_PATH"}; then
              echo "[retry] Reintentando (desktop) $path -> ${name}-d"
              lighthouse "${base}${path}" \
                --output=json --output=html \
                --output-path="lighthouse_reports/${name}-d" \
                --preset=perf \
                --emulated-form-factor=desktop \
                --throttling-method=devtools \
                --chrome-flags="--headless=new --no-sandbox --disable-gpu" \
                ${CHROME_PATH:+--chrome-path="$CHROME_PATH"}
            fi
            # Normalizar nombres
            mv "lighthouse_reports/${name}-d.report.json" "lighthouse_reports/${name}-d.json"
            mv "lighthouse_reports/${name}-d.report.html" "lighthouse_reports/${name}-d.html"
          }

          run_lh "/"              "home"
          run_lh "/en/"           "en-home"
          run_lh "/sobre-mi/"     "sobre-mi"
          run_lh "/en/about/"     "en-about"
          run_lh "/proyectos/"    "proyectos"
          run_lh "/en/projects/"  "en-projects"
          run_lh "/recursos/"     "recursos"
          run_lh "/en/resources/" "en-resources"
          run_lh "/contacto/"     "contacto"
          run_lh "/en/contact/"   "en-contact"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Assert Lighthouse thresholds
        run: |
          python3 scripts/assert_lh_thresholds.py

      - name: Generate Markdown summary
        if: always()
        run: |
          python3 scripts/summarize_lh_to_md.py

      - name: Publish Lighthouse HTML reports to docs
        if: always()
        run: |
          set -e
          mkdir -p docs/lighthouse
          cp -f lighthouse_reports/*.html docs/lighthouse/
          # Copiar resumen del assert si existe
          if [ -f lighthouse_reports/assert_summary.txt ]; then
            cp -f lighthouse_reports/assert_summary.txt docs/lighthouse/_assert_summary.txt
          fi

      - name: Upload Lighthouse artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse_reports
          path: lighthouse_reports

      - name: Commit updated reports and docs
        if: always()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git add docs/VALIDACION_MVP_v0_2_1.md docs/lighthouse/*.html docs/lighthouse/_assert_summary.txt || true
          if git diff --cached --quiet; then
            echo "No changes to commit in docs/"
          else
            git commit -m "chore(ci): actualizar reportes Lighthouse (móvil y desktop)"
            git push
          fi
