name: Rotate Application Password
on:
  workflow_dispatch: {}
jobs:
  rotate-app-password:
    runs-on: ubuntu-latest
    steps:
      - name: Instrucciones
        run: |
          echo "1) En WP-Admin (perfil del usuario CI), crear un nuevo Application Password."
          echo "2) Actualizar el secret WP_APP_PASSWORD en GitHub."
          echo "3) Validar /wp-json/wp/v2/users/me devuelve 200 con la nueva credencial."
      - name: Validación
        run: |
          set -euo pipefail
          [ -n "${WP_URL:-}" ] && [ -n "${WP_USER:-}" ] && [ -n "${WP_APP_PASSWORD:-}" ] || { echo KO; exit 2; }
          CODE=$(curl -sS -o /tmp/me.json -w "%{http_code}" -u "$WP_USER:$WP_APP_PASSWORD" "${WP_URL%/}/wp-json/wp/v2/users/me")
          test "$CODE" = 200 && echo "Auth: OK" || { echo "Auth: KO ($CODE)"; exit 2; }
        env:
          WP_URL: ${{ secrets.WP_URL }}
          WP_USER: ${{ secrets.WP_USER }}
          WP_APP_PASSWORD: ${{ secrets.WP_APP_PASSWORD }}
