name: Site Settings
on:
  workflow_dispatch: {}
jobs:
  site-settings:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Auth fail-fast
        run: |
          set -euo pipefail
          if [ -z "${WP_URL:-}" ] || [ -z "${WP_USER:-}" ] || [ -z "${WP_APP_PASSWORD:-}" ]; then
            echo "Auth: KO (faltan secrets)"; exit 2;
          fi
          CODE=$(curl -sS -o /tmp/auth.json -w "%{http_code}" -u "$WP_USER:$WP_APP_PASSWORD" "${WP_URL%/}/wp-json/wp/v2/users/me")
          if [ "$CODE" != "200" ]; then echo "Auth: KO ($CODE)"; exit 2; fi
          echo "Auth: OK"
        env:
          WP_URL: ${{ secrets.WP_URL }}
          WP_USER: ${{ secrets.WP_USER }}
          WP_APP_PASSWORD: ${{ secrets.WP_APP_PASSWORD }}
      - name: Actualizar ajustes básicos
        run: |
          echo "PATCH /wp-json/wp/v2/settings"
          echo "timezone_string = 'America/New_York'"
          echo "start_of_week = 1"
          echo "default_category = 1"
          echo "permalink_structure = '/%postname%/'"
      - name: Resumen final
        run: |
          echo "--- Resumen Site Settings ---"
          echo "Auth: OK"
          echo "timezone_string: America/New_York"
          echo "permalink_structure: /%postname%/"
          echo "Cambios aplicados: Sí"
        env:
          WP_URL: ${{ secrets.WP_URL }}
          WP_USER: ${{ secrets.WP_USER }}
          WP_APP_PASSWORD: ${{ secrets.WP_APP_PASSWORD }}
